name: Deploy EKS Cluster and Install Monitoring

on:
  workflow_run:
    workflows: ["Apply Terraform to AWS"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Get EC2 Public IP
      id: get_ec2_ip
      run: |
        


    - name: Connect to EC2 and set up EKS
      run: |
        # Configurar AWS CLI con las credenciales
        aws configure set aws_access_key_id ${{ secrets.AWS_KEY }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
        aws configure set region us-east-1

        EC2_IP=$(aws ec2 describe-instances \
          --filters "Name=tag:Name,Values=ubuntu_server_terraform" \
          --query 'Reservations[*].Instances[*].PublicIpAddress' \
          --output text)
        echo "EC2_IP=$EC2_IP" >> $GITHUB_ENV  # Almacenar IP en variable de entorno

        ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IP << 'EOF'
        # Actualizar el sistema
        sudo apt-get update -y

        # Crear un clúster EKS
        eksctl create cluster --name eks-mundos-e --region us-east-1 --node-type t3.small --nodes 3 --with-oidc --managed --full-ecr-access --zones us-east-1a,us-east-1b,us-east-1c

        # Added csi volumes
        eksctl create addon --name aws-ebs-csi-driver --cluster eks-mundos-e --region us-east-1
        
        # Añadir el repositorio de prometheus y grafana
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo update

        # Instalar Prometheus
        helm install prometheus prometheus-community/prometheus --namespace prometheus --create-namespace --set alertmanager.persistentVolume.storageClass="gp2" --set server.persistentVolume.storageClass="gp2"

        # Instalar Grafana
        helm install grafana grafana/grafana --namespace grafana  --create-namespace --set persistence.storageClassName="gp2" --set persistence.enabled=true --set adminPassword='EKS!sAWSome' --set service.type=LoadBalancer

        EOF

    - name: Finish
      run: echo "EKS Cluster created and Prometheus/Grafana installed"
