name: Destroy Terraform Resources on AWS

on:
  workflow_run:
    workflows: ["Deploy EKS Cluster and Install Monitoring"]
    types:
      - completed

jobs:
  terraform_destroy:
    name: Destroy Terraform Resources and Helm Releases
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Await Manual Approval for Destroy
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: "SRE-Adolfo-MX"
          minimum-approvals: 1  
          issue-title: "Approval needed: Destroy Terraform Resources"
          issue-body: "Please approve or deny the destruction of Terraform-managed resources in the AWS environment."
          exclude-workflow-initiator-as-approver: false

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Configure kubectl for EKS
        id: configure_kubectl
        run: |
          aws eks update-kubeconfig --name eks-mundos-e --region us-east-1

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Delete Prometheus and Grafana with Helm
        run: |
          helm delete prometheus --namespace prometheus || echo "Prometheus release not found"
          helm delete grafana --namespace grafana || echo "Grafana release not found"

      - name: Terraform Init
        working-directory: terraform/
        run: terraform init

      - name: Terraform Destroy
        if: ${{ success() }}  
        working-directory: terraform/
        run: terraform destroy -auto-approve

      - name: Delete EKS Cluster
        run: |
          eksctl delete cluster --name eks-mundos-e --region us-east-1
