name: List EKS Clusters

on:
  workflow_dispatch:
  
jobs:
  list-eks:
    name: List EKS Clusters Manually
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials from assumed role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.EKS_MGMT_USER }}
          aws-region: us-east-1

      - name: Scale to Zero EKS Clusters
        run: aws eks-sandbox-boris-nonprod % aws eks update-nodegroup-config \
            --cluster-name racks-upgrade-1-31-v2 \
            --nodegroup-name managed-1-20250519220454486300000008 \
            --scaling-config minSize=0,maxSize=0,desiredSize=1
